on:
  pull_request:
    branches:
      - main
    paths:
      - "migrations/*.sql"

jobs:
  bytebase-cicd:
    runs-on: ubuntu-latest
    env:
      BYTEBASE_URL: 'https://valid-just-tadpole.ngrok-free.app'
      BYTEBASE_PROJECT: 'projects/project-sample'
      BYTEBASE_SERVICE_ACCOUNT: 'api-example@service.bytebase.com'
      BYTEBASE_TARGETS: 'instances/test-sample-instance/databases/hr_test,instances/prod-sample-instance/databases/hr_prod'
      FILE_PATTERN: 'migrations/*.sql'
    name: Bytebase cicd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/login-action@main
        with:
          bytebase-url: ${{ env.BYTEBASE_URL }}
          service-key: ${{ env.BYTEBASE_SERVICE_ACCOUNT }}
          service-secret: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: sql review
        id: sql_review
        uses: bytebase/create-release-action@v1
        with:
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          project: ${{ env.BYTEBASE_PROJECT }}
          file-pattern: ${{ env.FILE_PATTERN }}
          # fail the action if release checks report any error.
          check-release: 'FAIL_ON_ERROR'
          targets: ${{ env.BYTEBASE_TARGETS }}
          validate-only: true
